= Tinypet

Projet Cloud ALMA 2023/2024

This guide outlines the necessary steps to run and deploy the application. Please ensure all instructions are followed for the application to function properly.

== Prerequisites
* Java 17 installed (Due to Google ending support for Java 8).
* Google Cloud SDK (gcloud) installed, authenticated, and configured with your project.
* Necessary APIs enabled in the Google Cloud Console.
* Relevant gcloud services and components installed on your local machine.

== Configuration Steps

. *Changing the Project ID in pom.xml*:
  - Update the `<projectID>` in `pom.xml` to your Google Cloud Project ID.

. *Installing Required APIs and Services*:
  - Make sure all required APIs are enabled in your Google Cloud Console.
  - Install any additional required gcloud components.

== Running the Application

. *Locally*:
  - For Windows, use `run.bat`.
  - For Unix-based systems, use `run.sh`.

== Deploying the Application

. *To Google App Engine*:
  - For Windows, use `deploy.bat`.
  - For Unix-based systems, use `deploy.sh`.

== Important Notes
- Ensure Java 17 is used, as the project is not compatible with Java 8.
- Failure to follow these instructions may result in the application not working correctly.

== Setting Up Angular Application

To run the Angular application located in the `tinypet-app` directory, you need to have Angular CLI installed.

. *Install Angular CLI*:
  - Angular CLI is required to run and build Angular projects. To install Angular CLI, run the following command: `npm install -g @angular/cli`
  - This will install Angular CLI globally on your system.

. *Running the Angular App*:
  - Navigate to the `tinypet-app` directory.
  - Run the following commands to install dependencies and start the application:
    `cd tinypet-app`
    `npm install`
    `ng serve`
  - The Angular application will be served on `http://localhost:4200` by default.


== Additional Recommendations
- Regularly update your Google Cloud SDK.
- Frequently check for the latest updates and patches for Java 17.
- Ensure you have Node.js and npm installed as they are prerequisites for Angular CLI.
- If you encounter any issues, check the version compatibility between your Angular project and the Angular CLI version.
