runtime: java17
basic_scaling:
  max_instances: 2
inbound_services:
- warmup
app_engine_apis: True
auto_id_policy: default
env_variables:
  'ENDPOINTS_SERVICE_NAME': 'tinypet-404519.appspot.com'
handlers:
- url: (/.*/)
  static_files: __static__\1app/index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1app/index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
