runtime: java17
basic_scaling:
  max_instances: 2
inbound_services:
- warmup
app_engine_apis: True
auto_id_policy: default
beta_settings:
  'source_reference': 'https://gitlab.univ-nantes.fr/E238898X/tinypet.git#bd2220c8fdd17de306edc0ff16e452f909ef40eb'
env_variables:
  'ENDPOINTS_SERVICE_NAME': 'tinypet-404519.appspot.com'
handlers:
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
